-- Манифест ЗнатокOS
-- Используется installer.lua для разворачивания файлов,
-- а также pkg.manager для обновлений.
return {
    name = "znatokos",
    version = "0.1.0",
    root = "/znatokos",
    startup = "/startup.lua",
    files = {
        -- Корень
        "startup.lua",
        "manifest.lua",
        -- Ядро
        "src/kernel/boot.lua",
        "src/kernel/scheduler.lua",
        "src/kernel/window.lua",
        "src/kernel/ipc.lua",
        "src/kernel/log.lua",
        -- FS
        "src/fs/vfs.lua",
        "src/fs/paths.lua",
        -- Util
        "src/util/cyrillic.lua",
        -- Auth
        "src/auth/sha256.lua",
        "src/auth/users.lua",
        "src/auth/login.lua",
        -- UI
        "src/ui/theme.lua",
        "src/ui/widgets.lua",
        "src/ui/dialog.lua",
        "src/ui/desktop.lua",
        "src/ui/taskbar.lua",
        -- Shell
        "src/shell/shell.lua",
        "src/shell/builtins.lua",
        "src/shell/commands/ls.lua",
        "src/shell/commands/cd.lua",
        "src/shell/commands/cat.lua",
        "src/shell/commands/mkdir.lua",
        "src/shell/commands/rm.lua",
        "src/shell/commands/mv.lua",
        "src/shell/commands/cp.lua",
        "src/shell/commands/edit.lua",
        "src/shell/commands/run.lua",
        "src/shell/commands/lua.lua",
        "src/shell/commands/help.lua",
        "src/shell/commands/clear.lua",
        "src/shell/commands/reboot.lua",
        "src/shell/commands/shutdown.lua",
        "src/shell/commands/ps.lua",
        "src/shell/commands/kill.lua",
        "src/shell/commands/top.lua",
        "src/shell/commands/pkg.lua",
        "src/shell/commands/net.lua",
        "src/shell/commands/chat.lua",
        "src/shell/commands/sendfile.lua",
        "src/shell/commands/passwd.lua",
        "src/shell/commands/useradd.lua",
        "src/shell/commands/whoami.lua",
        "src/shell/commands/logout.lua",
        -- Net
        "src/net/rednet.lua",
        "src/net/chat.lua",
        "src/net/filetransfer.lua",
        "src/net/remote.lua",
        -- Pkg
        "src/pkg/manager.lua",
        "src/pkg/repo.lua",
        "src/pkg/repo_default.lua",
        -- Apps
        "src/apps/terminal.lua",
        "src/apps/filemanager.lua",
        "src/apps/settings.lua",
        "src/apps/clock.lua",
        "src/apps/calc.lua",
        "src/apps/snake.lua",
        "src/apps/paint.lua",
        -- Tests
        "tests/run_tests.lua",
        "tests/test_shell.lua",
        "tests/test_sha256.lua",
        "tests/test_vfs.lua",
        "tests/test_pkg.lua",
    },
}
