return {
    id = "com.znatok.browser",
    name = "Браузер",
    version = "1.5.0",
    author = "znatok",
    description = "Web-браузер: HTML+CSS, картинки NFP, вкладки, масштаб, HDMonitor true-color режим",
    icon = { color = colors.lightBlue, glyph = "W" },
    entry = "main.lua",
    files = {
        "main.lua",
        "lib/http.lua",
        "lib/url.lua",
        "lib/html.lua",
        "lib/layout.lua",
        "lib/render.lua",
        "lib/hdrender.lua",
        "lib/link.lua",
        "lib/form.lua",
        "lib/js.lua",
        "lib/css.lua",
        "lib/tabs.lua",
        "lib/search.lua",
        "lib/store.lua",
        "lib/palette.lua",
        "lib/image.lua",
        "themes/default.lua",
    },
    capabilities = { "ui.window", "net.http", "fs.home", "periph.speaker", "periph.advanced" },
    min_os_version = "0.3.0",
    deps = {},
}
