return {
    id = "com.znatok.browser",
    name = "Браузер",
    version = "0.3.0",
    author = "znatok",
    description = "Web-браузер: HTML+CSS, ссылки, формы, вкладки, история",
    icon = { color = colors.lightBlue, glyph = "W" },
    entry = "main.lua",
    files = {
        "main.lua",
        "lib/http.lua",
        "lib/url.lua",
        "lib/html.lua",
        "lib/layout.lua",
        "lib/render.lua",
        "lib/link.lua",
        "lib/form.lua",
        "lib/js.lua",
        "lib/css.lua",
        "lib/tabs.lua",
        "themes/default.lua",
    },
    capabilities = { "ui.window", "net.http", "fs.home" },
    min_os_version = "0.3.0",
    deps = {},
}
